WaiterQR/Models/RestaurantTableViewModel.cs
// The RestaurantTableViewModel contains the important attributes of the RestaurantTable dataframe within the sql database
// Authors: Dennis Keles, Dennis Ludwig, Sheng Jing Ly


using DocumentFormat.OpenXml.Bibliography;
using Microsoft.Owin.BuilderProperties;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WaiterQR.Database;

namespace WaiterQR.Models
{
    public class RestaurantTableViewModel
    {
        [Key]
        [Display(Name = "RestaurantID")]
        public int ResID { get; set; }

        [Required(ErrorMessage = "RestaurantTable_ID is required.")]
        public int RestaurantTable_ID { get; set; }

        [Required(ErrorMessage = "RestaurantTable_Occupied is required.")]
        public Boolean RestaurantTable_Occupied { get; set; }

        public List<RestaurantTable> RestaurantTables { get; set; }

        public int capacity { get; set; }
    }

}

WaiterQR/Controllers/QrCodeController.cs
// In this class the QR code is generated. It takes the link which is needed by the customers to get to the menu and encodes it as a qr code.
// In the end it creates a bitmap image which is visualized and accessible for the restaurant owners
// Authors: Dennis Keles, Dennis Ludwig, Sheng Jing Ly

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using System.IO;
using QRCoder;

namespace WaiterQR.Controllers
{
    [Authorize] //only accessible with login

    public class QrCodeController : Controller
    {
        // It takes the link which is needed by the customers to get to the menu and encodes it as a qr code. 
        public ActionResult CreateQrCode(int tableid)
        {
            string qrText = "http://" + Request.Url.Host + (Request.Url.IsDefaultPort ? "" : ":" + Request.Url.Port) + "/menu/showmenu?tableid=" +tableid;
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(qrText,QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);
            ViewBag.message = qrText;
            return View(BitmapToBytes(qrCodeImage));
        }
        // Gives out a bitmap for the qr code
        private static Byte[] BitmapToBytes(Bitmap img)
        {
           
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
    }
}

WaiterQR/Controllers/RestaurantTableController.cs
// This class defines the product handling such as Editing, Deleting, Adding and Showing of different RestaurantTables.
// Authors: Dennis Keles, Dennis Ludwig, Sheng Jing Ly

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaiterQR.Database;
using WaiterQR.Models;

namespace WaiterQR.Controllers
{
    [Authorize] //only accessible with login

    public class RestaurantTableController : Controller
    {
        // GET: Gives out the restaurant tables for a specific restaurant based on the given restaurant id
        public ActionResult ShowRestaurantTable(int restaurantid)
        {
            try
            {
                var tempList = new List<RestaurantTable>();
                using (websitedbEntities db = new websitedbEntities())
                {
                    foreach (RestaurantTable rt in db.RestaurantTable)
                    {
                        if (rt.RestaurantID == restaurantid)
                        {
                            tempList.Add(rt);
                        }
                        
                    }
                }
                RestaurantTableViewModel rtvw = new RestaurantTableViewModel();
                rtvw.ResID = restaurantid;
                rtvw.RestaurantTables = tempList;
                return View(rtvw);
            }


            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());
                return View();

            }        
        }

        // GET: Opens the EditRestaurantTable view and gives the user the option to reset the attributes. The restaurant id clearly identifies the restaurant to change and
        // therefore the fields are auto completed
        public ActionResult EditRestaurantTable(int restaurantid)
        {
            try
            {
                var tempList = new List<RestaurantTable>();
                int tableamount = 0;
                using (websitedbEntities db = new websitedbEntities())
                {              
                    tableamount = db.RestaurantTable.Where(x => x.RestaurantID == restaurantid).Count();

                }
                RestaurantTableViewModel rv = new RestaurantTableViewModel();
                rv.ResID = restaurantid;
                rv.capacity = tableamount;
                return View(rv);

            }

            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());

            }
            return View();

        }
        // POST: RestaurantTable/Edit Edits the product in the database based on the user input
        [HttpPost]
        public ActionResult EditRestaurantTable(RestaurantTableViewModel restaurantTableViewModel)
        {
            try
            {
                var tempList = new List<RestaurantTable>();
                int tableamount = 0;
                using (websitedbEntities db = new websitedbEntities())
                {

                    tableamount = db.RestaurantTable.Where(x => x.RestaurantID == restaurantTableViewModel.ResID).Count();

                    if (tableamount < restaurantTableViewModel.capacity)
                    {

                        while (tableamount < restaurantTableViewModel.capacity)
                        {
                            RestaurantTable rt = new RestaurantTable();
                            rt.RestaurantID = restaurantTableViewModel.ResID;
                            rt.RestaurantSeat = tableamount + 1;
                            tableamount = tableamount + 1;

                            db.RestaurantTable.Add(rt);
                            db.SaveChanges();
                        }
                        ViewBag.message = "Successfully increased to " + restaurantTableViewModel.capacity + " Tables";
                        ViewBag.resid = restaurantTableViewModel.ResID;

                    }
                    else if (tableamount > restaurantTableViewModel.capacity)
                    {
                        List<RestaurantTable> tableList = db.RestaurantTable.ToList();

                        foreach (RestaurantTable rt in tableList)
                        {
                            if(rt.RestaurantID == restaurantTableViewModel.ResID)
                            {                      
                              db.RestaurantTable.Remove(rt);
                              db.SaveChanges();
                            }
                        }

                        tableamount = 0;
                        while (tableamount < restaurantTableViewModel.capacity)
                        {
                            RestaurantTable rt = new RestaurantTable();
                            rt.RestaurantID = restaurantTableViewModel.ResID;
                            rt.RestaurantSeat = tableamount + 1;
                            tableamount = tableamount + 1;

                            db.RestaurantTable.Add(rt);
                            db.SaveChanges();
                        }
                        ViewBag.message = "Successfully decreased to "+ restaurantTableViewModel.capacity + " Tables";
                        ViewBag.resid = restaurantTableViewModel.ResID;

                    }
                   else if (tableamount == restaurantTableViewModel.capacity)
                    {
                        ViewBag.message = "Please enter a different Table Capacity Number than the current one";
                        ViewBag.resid = restaurantTableViewModel.ResID;

                    }
                }
            }

            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());

            }
            return View();

        }

    }
}

WaiterQR/Views/RestaurantTable/EditRestaurantTable.cshtml
@*Gives the option to edit the amount of restaurant tables for a specific restaurant.
    Authors: Dennis Ludwig, Dennis Keles, Sheng Jing Ly*@

    @model WaiterQR.Models.RestaurantTableViewModel

    @{
        ViewBag.Title = "EditRestaurantTable";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>EditRestaurantTable</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>RestaurantTableViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ResID)
            @Html.HiddenFor(model => model.RestaurantTable_ID)
            @Html.HiddenFor(model => model.RestaurantTable_Occupied)


            <div class="form-group">
                @Html.LabelFor(model => model.capacity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.capacity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.capacity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="btn btn-dark" type="submit" value="Save" />
                </div>
                <br />
            </div>
            @*<div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-secondary">
                        @Html.ActionLink("Back", "ShowRestaurantTable", "RestaurantTable", new { restaurantid = Model.ResID }, null)
                    </button>
                </div>*@
            <div>
                @if (ViewBag.message != null)
                {
                    <h4>@ViewBag.message</h4>
                    @Html.ActionLink("Return to the list", "ShowRestaurantTable", "RestaurantTable", new { restaurantid = ViewBag.resid }, null)
                }
            </div>
        </div>
    }

WaiterQR/Views/RestaurantTable/ShowRestaurantTable.cshtml
@*Gives the option to show the available restaurant tables and the reffering qrcodes.
    Authors: Dennis Ludwig, Dennis Keles, Sheng Jing Ly*@


@model WaiterQR.Models.RestaurantTableViewModel

@{
    ViewBag.Title = "ShowRestaurantTable";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ShowRestarauntTable</h2>
<h3>Currently you registered @Model.RestaurantTables.Count tables </h3>

<h3>
    <button class="btn btn-dark">@Html.ActionLink("Change amount of Tables", "EditRestaurantTable", "RestaurantTable", new { restaurantid = Model.ResID }, null)</button>
</h3>


<!DOCTYPE html>

<html>
<head>
    <style>
        table {
            width: 100%;
        }

        td, th {
            text-align: center;
            padding: 15px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
    <table>
        <tr>
            <th>Restaurant</th>
            <th>Table</th>

        </tr>
        @foreach (var item in Model.RestaurantTables)
        {
            <tr>
                <td> @item.RestaurantID </td>
                <td> @item.RestaurantSeat </td>

                <td>
                    <button class="btn btn-dark">
                        @Html.ActionLink("Show QR Code", "CreateQRCOde", "QrCode", new { tableid = item.ID }, null)
                    </button>
                </td>
            </tr>
        }

    </table>

</body>
</html>