WaiterQR/Controllers/ActiveOrderController.cs
// This class is used for handling the activeorders by the restaurant owners. This includes showing the open orders for a restaurant and setting the order
// as done by the restaurant owner. 
// Authors: Dennis Keles, Dennis Ludwig, Sheng Jing Ly

using DocumentFormat.OpenXml.Drawing.Charts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaiterQR.Database;
using WaiterQR.Models;

namespace WaiterQR.Controllers
{
    [Authorize] //only accessible with login

    public class ActiveOrderController : Controller
    {

        // GET: Gives out the products ordered by the users. Additionally it gives information on the amount and the table ordered from
        public ActionResult ShowActiveOrder(int restaurantid)
        {
            List<ActiveOrderViewModel> tempList = new List<ActiveOrderViewModel> ();
            try
            {  
                using (websitedbEntities db = new websitedbEntities())
                {
                    List<Product> productList = db.Product.ToList();
                    List<ShoppingCart> shoppingCarts = db.ShoppingCart.ToList();
                    List<RestaurantTable> restaurantTables = db.RestaurantTable.ToList();
                    
                    foreach (ShoppingCart sc in shoppingCarts)
                    {
                        if (sc.OrderStatus==1)
                        {
                            if (sc.RestaurantID == restaurantid)
                            {
                                foreach (Product p in productList)
                                {
                                    if (p.ProductID == sc.ProductIDs)
                                    {
                                        ActiveOrderViewModel aovw = new ActiveOrderViewModel();
                                        aovw.Tableid = db.RestaurantTable.Find(sc.RestaurantIDTable).RestaurantSeat;  
                                        aovw.Productname = p.ProductName;
                                        aovw.Amount = sc.ProductCount;
                                        aovw.Status = sc.OrderStatus;
                                        aovw.OrderID = sc.ShoppingCartID;
                                        tempList.Add(aovw);
                                    }
                                }
                            }
                        }
                    }

                    return View(tempList);
                }

            }

            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());
                return View();

            }
        }
        // Sets order elements as finished and therefore it is removed from the activeorder list
        public ActionResult FinishOrder(int orderid)
        {
            ShoppingCart sc = new ShoppingCart();
            try
            {

                using (websitedbEntities db = new websitedbEntities())
                {
                    sc = db.ShoppingCart.Find(orderid);
                    sc.OrderStatus = 0;
                    db.SaveChanges();
                }
                return RedirectToAction("ShowActiveOrder", new { restaurantid = sc.RestaurantID });
            }
            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());
                return RedirectToAction("ShowActiveOrder", new { restaurantid = sc.RestaurantID });
            }


        }
    }
}

WaiterQR/Controllers/ProductController.cs
// This class defines the product handling such as Editing, Adding, Deleting and Showing of different products.
// Authors: Dennis Keles, Dennis Ludwig, Sheng Jing Ly

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using WaiterQR.Database;
using WaiterQR.Models;
using System.IO;


namespace WaiterQR.Controllers
{
    [Authorize] //only accessible with login

    public class ProductController : Controller
    {
        
        // GET: Gives out the products for a specific restaurant based on the given restaurant id
        public ActionResult ShowProduct(int? restaurantid)
        {
            if (restaurantid == null)
            {
                try
                {
                    var tempList = new List<Product>();
                    using (websitedbEntities db = new websitedbEntities())
                    {
                        foreach (Product p in db.Product)
                        {
                            tempList.Add(p);

                        }
                    }
                    return View(tempList);
                }


                catch (Exception e)
                {
                    string s = string.Format("Fehler: {0}", e.Message);
                    s = string.Format("Typ: {0}", e.GetType());
                    return View();

                }
            }
            else
            {
                try
                {
                    var tempList = new List<Product>();
                    using (websitedbEntities db = new websitedbEntities())
                    {
                        foreach (Product p in db.Product)
                        {
                            if (p.RestaurantID == restaurantid)
                            {
                                tempList.Add(p);
                            }
                        }
                    }

                    using (websitedbEntities db = new websitedbEntities())
                    {
                        ViewBag.RestaurantName = db.Restaurant.Find(restaurantid).Name;
                    }
                    return View(tempList);
                }


                catch (Exception e)
                {
                    string s = string.Format("Fehler: {0}", e.Message);
                    s = string.Format("Typ: {0}", e.GetType());
                    return View();

                }
            }
        }



        // GET: Opens the addproduct view and gives the user the option to set the attributes
        public ActionResult AddProduct()
        {
            return View();
        }

        // POST: Product/Create Creates the product in the database based on the user input
        [HttpPost]
        public ActionResult AddProduct(Product product)
        {
            try

            {

                byte[] imgData;
                using (BinaryReader reader = new BinaryReader(product.ImageFile.InputStream))
                {
                    imgData = reader.ReadBytes((int)product.ImageFile.InputStream.Length);
                }

                using (websitedbEntities db = new websitedbEntities())
                {

                    Product prod = new Product();
                    prod.RestaurantID = product.RestaurantID;
                    prod.ProductDescription = product.ProductDescription;
                    prod.ProductName = product.ProductName;
                    prod.ImagePath = Convert.ToBase64String(imgData);

                    if ((decimal.Parse(product.ProductPrice) > 0 && !product.ProductPrice.Contains('.'))){
                        prod.ProductPrice = product.ProductPrice;
                        db.Product.Add(prod);
                        db.SaveChanges();
                        return RedirectToAction("ShowProduct", new { restaurantid = prod.RestaurantID });

                    }
                    else
                    {
                        ViewBag.PriceError = "Please enter a price in the format xxx,yy";
                        return View();
                    }


                }
              
            }
            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());

                return View();
            }
        }

        // GET: Opens the editproduct view and gives the user the option to reset the attributes. The product id clearly identifies the product to change and
        // therefore the fields are auto completed
        public ActionResult EditProduct(int productID)
        {
            if (!productID.Equals(null))
            {
                try
                {
                    websitedbEntities db = new websitedbEntities();


                    var prod = db.Product.SingleOrDefault(x => x.ProductID == productID);

                    return View(prod);

                }

                catch (Exception e)
                {
                    string s = string.Format("Fehler: {0}", e.Message);
                    s = string.Format("Typ: {0}", e.GetType());
                    return View();
                }

            }
            return View();
        }
        // POST: Product/Edit Edits the product in the database based on the user input
        [HttpPost]
        public ActionResult EditProduct(Product product)
        {

            try
            {
                byte[] imgData;
                using (BinaryReader reader = new BinaryReader(product.ImageFile.InputStream))
                {
                    imgData = reader.ReadBytes((int)product.ImageFile.InputStream.Length);
                }
                using (websitedbEntities db = new websitedbEntities())
                {
                    Product prod = db.Product.SingleOrDefault(x => x.ProductID == product.ProductID);

                    prod.RestaurantID = product.RestaurantID;
                    prod.ProductDescription = product.ProductDescription;
                    prod.ProductName = product.ProductName;
                    prod.ProductPrice = product.ProductPrice;
                    prod.ImagePath = Convert.ToBase64String(imgData);
                   
                    if ((decimal.Parse(product.ProductPrice) > 0 && !product.ProductPrice.Contains('.')))
                    {
                        prod.ProductPrice = product.ProductPrice;
                        db.SaveChanges();

                        ViewBag.message = "Restaurant information updated successfully.";
                        return RedirectToAction("ShowProduct", new { restaurantid = prod.RestaurantID });

                    }
                    else
                    {
                        ViewBag.PriceError = "Please enter a price in the format xxx,yy";
                        return View();
                    }

                }
            }
            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());
                return View();
            }
        }

        // Product/Delete Deletes the product in the database based on the given product id
        public ActionResult DeleteProduct(int productID)
        {
            try
            {
                using (websitedbEntities db = new websitedbEntities())
                {
                    Product p = db.Product.Find(productID);
                    db.Product.Remove(p);
                    db.SaveChanges();
                }
                return RedirectToAction("ShowProduct");

            }
            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());
                return RedirectToAction("ShowProduct");

            }

        }
    }
}

    

WaiterQR/Controllers/RestaurantController.cs
// This class defines the product handling such as Editing, Deleting and Showing of different restaurants.
// Authors: Dennis Keles, Dennis Ludwig, Sheng Jing Ly

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using System.Windows.Media.Animation;
using WaiterQR.Database;
using WaiterQR.Models;

namespace WaiterQR.Controllers
{
    [Authorize] //only accessible with login

    public class RestaurantController : Controller
    {
        // GET: Opens the addproduct view and gives the user the option to set the attributes
        public ActionResult AddRestaurant()
        {
            return View();
        }
        // POST: Product/Create Creates the product in the database based on the user input
        [HttpPost]
        public ActionResult AddRestaurant(Restaurant restaurants)
        {
            try
            {
                using (websitedbEntities db = new websitedbEntities())
                {

                    Restaurant restaurant = new Restaurant();

                    
                    restaurant.OwnerID = restaurants.OwnerID;
                    restaurant.PostalCode = restaurants.PostalCode;
                    restaurant.City = restaurants.City;
                    restaurant.StreetName = restaurants.StreetName;
                    restaurant.HouseNo = restaurants.HouseNo;
                    restaurant.TableAmount = 0;
                    restaurant.Name = restaurants.Name;
                    restaurant.Description = restaurants.Description;

                   

                    db.Restaurant.Add(restaurant);
                    db.SaveChanges();


                }

            }

            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());

            }
            return RedirectToAction("ShowRestaurant");

        }
        // GET: Gives out all the restaurant in the db
        public ActionResult ShowRestaurant()
        {
            try
            {
                var tempList = new List<Restaurant>();
                using (websitedbEntities db = new websitedbEntities())
                {
                    foreach (Restaurant r in db.Restaurant)
                    {
                        tempList.Add(r);
                    }
                }
                return View(tempList);
            }


            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());
                return View();

            }

        }
        // GET: Opens the EditRestaurant view and gives the user the option to reset the attributes. The restaurant id clearly identifies the product to change and
        // therefore the fields are auto completed
        public ActionResult EditRestaurant(int restaurantid)
        {
            if (!restaurantid.Equals(null))
            {
                try
                {
                    websitedbEntities db = new websitedbEntities();


                    var res = db.Restaurant.SingleOrDefault(x => x.ID == restaurantid);

                    return View(res);

                }

                catch (Exception e)
                {
                    string s = string.Format("Fehler: {0}", e.Message);
                    s = string.Format("Typ: {0}", e.GetType());
                    return View();
                }

            }
            else
            {
                return View();
            }


    }
        // POST: REstaurant/Edit Edits the product in the database based on the user input
        [HttpPost]
        public ActionResult EditRestaurant(Restaurant restaurants)
        {
            try
            {
                websitedbEntities db = new websitedbEntities();



                Restaurant restaurant = db.Restaurant.Find(restaurants.ID);

                restaurant.OwnerID = restaurants.OwnerID;
                restaurant.PostalCode = restaurants.PostalCode;
                restaurant.City = restaurants.City;
                restaurant.StreetName = restaurants.StreetName;
                restaurant.HouseNo = restaurants.HouseNo;
                restaurant.TableAmount = restaurants.TableAmount;
                restaurant.Name = restaurants.Name;
                restaurant.Description = restaurants.Description;

                db.SaveChanges();

                ViewBag.message = "Restaurant information updated successfully.";
                return View(restaurant);

            }

            catch (Exception e)
            {
                string s = string.Format("Fehler: {0}", e.Message);
                s = string.Format("Typ: {0}", e.GetType());
                return View();
            }


        }

        // Restaurant/Delete Deletes the product in the database based on the given product id
        public ActionResult DeleteRestaurant(int restaurantid)
        {
            using(websitedbEntities db = new websitedbEntities())
            {
                db.Restaurant.Remove(db.Restaurant.Find(restaurantid));
                db.SaveChanges();

            }
            return RedirectToAction("ShowRestaurant");

        }
    }


}

WaiterQR/Views/Restaurant/AddRestaurant.cshtml
@*Gives the option to put in attributes for adding a restaurant. Additionally it enables the users to add a picture for the restaurant.
    Authors: Dennis Ludwig, Dennis Keles, Sheng Jing Ly*@

@model WaiterQR.Models.RestaurantViewModel

@{
    ViewBag.Title = "AddRestaurant";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddRestaurant</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>RestaurantModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HouseNo, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.TableAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TableAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TableAmount, "", new { @class = "text-danger" })
                </div>
            </div>*@



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ShowRestaurant", "Restaurant")
</div>

@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

WaiterQR/Views/Restaurant/EditRestaurant.cshtml
@*Gives the option to edit attributes for a specific restaurant. Additionally it enables the users to alter a picture for the restaurant.
    Authors: Dennis Ludwig, Dennis Keles, Sheng Jing Ly*@

@model WaiterQR.Database.Restaurant

@{
    ViewBag.Title = "EditRestaurant";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditRestaurant</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HouseNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TableAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TableAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TableAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-dark" />
            </div>
        </div>
        <div>
            @if (ViewBag.message != null)
            {
                <h4>@ViewBag.message</h4>
            }
        </div>
    </div>

}
<h3>
    <button class="btn btn-dark">@Html.ActionLink("Delete my Restaurant", "DeleteRestaurant", "Restaurant", new { restaurantid = Model.ID }, null)</button>
</h3>
<div>
    @Html.ActionLink("Back to List", "ShowRestaurant", "Restaurant")
</div>

WaiterQR/Views/Restaurant/ShowRestaurant.cshtml
@*Gives the option to show the available restaurants to manage them.
    Authors: Dennis Ludwig, Dennis Keles, Sheng Jing Ly*@

@model  List<WaiterQR.Database.Restaurant>

@{
    ViewBag.Title = "ShowRestaurant";
}

<h2>ShowRestaurant</h2>
<h3>
    <button class="btn btn-dark">@Html.ActionLink("Register a new Restaurant", "AddRestaurant", "Restaurant")</button>
</h3>


<!DOCTYPE html>

<html>
<head>
    <style>
        table {
            width: 100%;
        }

        td, th {
            text-align: center;
            padding: 15px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>

            <th>Owner</th>
            <th>Location</th>
            <th>House</th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td> @item.ID </td>
                <td> @item.Name </td>
                <td> @item.Description </td>

                <td> @item.OwnerID </td>
                <td> @item.PostalCode, @item.City</td>
                <td> @item.StreetName, @item.HouseNo</td>
                <td>
                    <button class="btn btn-dark">
                        @Html.ActionLink("Edit Restaurant", "EditRestaurant", "Restaurant", new { restaurantid = item.ID }, null)
                    </button>
                </td>
                <td>
                    <button class="btn btn-dark">
                        @Html.ActionLink("Manage Products", "ShowProduct", "Product", new { restaurantid = item.ID }, null)
                    </button>
                </td>
                <td>
                    <button class="btn btn-dark">
                        @Html.ActionLink("Show Tables", "ShowRestaurantTable", "RestaurantTable", new { restaurantid = item.ID }, null)
                    </button>
                </td>
                <td>
                    <button class="btn btn-dark">
                        @Html.ActionLink("Show Orders", "ShowActiveOrder", "ActiveOrder", new { restaurantid = item.ID }, null)
                    </button>
                </td>

            </tr>
        }

    </table>

</body>
</html>

WaiterQR/Views/Restaurant/ShowRestaurant2.cshtml
@model IEnumerable<WaiterQR.Models.RestaurantModel>

@{
    ViewBag.Title = "ShowRestaurant2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ShowRestaurant2</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OwnerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RestaurantPostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant_City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant_StreetName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant_HouseNo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RestaurantPostalCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant_City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant_StreetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant_HouseNo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ResID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ResID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ResID })
        </td>
    </tr>
}

</table>

WaiterQR/Views/Restaurant/ndnafgd.cshtml
@model IEnumerable<WaiterQR.Models.RestaurantModel>

@{
    ViewBag.Title = "ndnafgd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ndnafgd</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OwnerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RestaurantPostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant_City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant_StreetName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Restaurant_HouseNo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RestaurantPostalCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant_City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant_StreetName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Restaurant_HouseNo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ResID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ResID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ResID })
        </td>
    </tr>
}

</table>